#!/bin/sh

print_usage() {
    echo "Usage:  ./run [-d] <A rows> <A cols> <B rows> <B cols>"
    echo ""
    echo "Runs matMul, optionally in debug mode, with the given matrix dimensions"
    echo ""
    echo "Option: -d  Run in debug mode."
}

case $# in
    4)
        make clean && make && ./matMul $1 $2 $3 $4
        ;;
    5)
        if [ "$1" = "-d" ]; then
            make clean && make FLAG="-DDEBUG" && ./matMul $2 $3 $4 $5
        else
            print_usage
            exit 1
        fi
        ;;
    *)
        print_usage
        exit 1
        ;;
esac
